apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumia-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: www.lumiatechs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lumia-app-service
            port:
              number: 8080
