app:
  image: ndzenyuy/lumia-app:368c558ff5b8961211c38e81c18d1b5e19eb7d85
  replicas: 5
  port: 8080

db:
  image: ndzenyuy/lumia-db:368c558ff5b8961211c38e81c18d1b5e19eb7d85
  port: 3306
  name: accounts
  user: admin
  password: admin123
  storage: 3Gi
  storageClass: gp2
  replicas: 5

ingress:
  host: www.lumiatechs.com
  className: nginx
