app:
  image: ndzenyuy/lumia-app:18ad0f5
  replicas: 6
  port: 8080

db:
  image: ndzenyuy/lumia-db:18ad0f5
  port: 3306
  name: accounts
  user: admin
  password: admin
  storage: 3Gi
  storageClass: gp2
  replicas: 3

ingress:
  host: www.lumiatechs.com
  className: nginx
